Add weather icons to the Schedule and Team Schedule pages
mjhale/blaseball-reference.com pull request #1
Opened 2020-09-22 03:01 UTC by nightpool

I saw a lot of people asking for this information on the SIBR discord this morning, but it's currently only easily availible on the janky schedule spreadsheet that's pinned in the main discord.

<img width="1151" alt="image" src="https://user-images.githubusercontent.com/233815/93840399-47cd8c80-fc5e-11ea-8c41-930b2117165b.png">
<img width="1151" alt="image" src="https://user-images.githubusercontent.com/233815/93840422-5156f480-fc5e-11ea-914e-809ba0422ac0.png">

Let me know what you think! Totally happy to make changes to code layout/styling/etc. This is my first contribution so let me know what fits best with your project! I thought about adding a script to calculate the `WEATHERS` array, but since I sourced it by just putting a breakpoint into the main site JS, I don't think this information is easily obtainable by script 😔. Let me know if you can think of a better way!

For icons, this uses the same `react-icons` depedency that blaseball.com uses. This makes things very easy, because I can just map from the `displayName` of the Blaseball.com React component to the corresponding react-icons component name.

2020-09-22 03:03 UTC, nightpool commented
The specific code I ran to generate the weathers array was `Object.fromEntries(ye.map((o, i) => [i, {...o, icon: o.icon.type.displayName}]))`

2020-09-22 03:14 UTC, Tantusar commented
This probably shouldn't (by default) show future weather beyond the next game.

2020-09-22 03:58 UTC, nightpool commented
After some discussion in the SIBR discord, i'm working on adding a forbidden knowledge opt-in toggle to the footer of the page.

2020-09-22 04:08 UTC, nightpool commented
![fk2](https://user-images.githubusercontent.com/233815/93843386-aba88300-fc67-11ea-974c-b3db206e76dc.gif)

2020-09-22 15:04 UTC, nightpool commented
@mjhale I added and ran prettier based on your feedback on Discord, lmk what you think!

2020-09-23 01:07 UTC, mjhale requested changes
Thank you for working on this and for including the Discord channel's feedback! Overall everything looks really good. I just have a few minor suggestions in the review as well as a question about the placement of the toggle.

2020-09-23 01:07 UTC, mjhale commented on components/Footer/Footer.js
> +          </Link>
Let's use a `<Button as={Link} />` component here since it doesn't direct the user to another page.

Also, should we only render this on pages that include future event details? If so, the easiest route would likely be moving it into a separate component (e.g., ForbiddenKnowledgeToggle) and including it beneath relevant areas. See the attached screenshot for an example of the placement.

<img width="1104" alt="A 'forbidden knowledge' toggle shown above the footer" src="https://user-images.githubusercontent.com/1341869/93952420-c84fc400-fd16-11ea-8b63-10c034df657a.png">

2020-09-23 01:07 UTC, mjhale commented on pages/schedule.js
> +import useForbiddenKnowledge from "hooks/useForbiddenKnowledge";
This is an insignificant style nitpick that spans the PR, so please feel free to pass over it for any reason: In general I like to group imports into two categories: everything that's not a component, and then components.

2020-09-23 01:07 UTC, mjhale commented on pages/schedule.js
> +                </Box>
```suggestion
                <Flex flex="1 1 0%">
                  <WeatherIcon for={game.weather} />
                  <Text color="gray.600" as="span" fontSize="sm" ml="2">
                    <WeatherName for={game.weather} />
                  </Text>
                </Flex>
```

2020-09-23 01:07 UTC, mjhale commented on components/weather.js
> +};
This approach is good! We'll just need to remember to update the list whenever a new weather event is added. Eventually we'll be able to grab this information from the SIBR database.

2020-09-23 01:07 UTC, mjhale commented on components/Footer/Footer.js
> +  const [fK, setFK] = useForbiddenKnowledge();
```suggestion
  const [showForbiddenKnowledge, setShowForbiddenKnowledge] = useForbiddenKnowledge();
```

2020-09-23 01:40 UTC, nightpool commented on components/Footer/Footer.js
> +          </Link>
the idea is that it needs to be a `button` element in the DOM for accessibility reasons, but it should be styled like a link. Therefore, `Chakra.Link` as `button`. I'm not sure exactly how `<Button as={Link}` would work.... that means it's an `<a href=` in dom but styled like a button, which seems like the opposite of what we want?

2020-09-23 01:41 UTC, nightpool commented on pages/schedule.js
> +import useForbiddenKnowledge from "hooks/useForbiddenKnowledge";
ah, i generally like to group by "Libraries" and "local imports" so that's what I did here. Happy to change.

2020-09-23 01:43 UTC, nightpool commented on components/weather.js
> +};
yes, unfortunately I think the API doesn't contain this information but I have some thoughts on ways we can improve this process and make sure it stays up to date, if I get the time to implement them

2020-09-23 01:44 UTC, nightpool commented on components/Footer/Footer.js
> +  const [fK, setFK] = useForbiddenKnowledge();
Just felt like a lot of repetition for something that was v. obvious from context (every line on which `fK` is used also has forbidden knowledge spelled out somewhere else) but happy to change.

2020-09-23 01:52 UTC, mjhale commented on components/Footer/Footer.js
> +          </Link>
You're exactly right. The existence of the `href` prop threw me off when making that suggestion. Is that prop required?

2020-09-29 01:49 UTC, merged